[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["munvoseli <muslinmelody@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "^0"
sdl2 = "^0"
webpki-roots = "^0"
rustls = "^0"
native-tls = "^0"
json = "^0"

[dependencies.mio]
version = "0.8"
features = ["os-poll", "net"]
